-- ==================================================================
-- TABLES - MySQL
-- ==================================================================

-- RB_USER
DROP TABLE IF EXISTS `RB_USER`;
CREATE TABLE IF NOT EXISTS `RB_USER` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER					VARCHAR(50) NOT NULL,
	CREATE_TIME					DATETIME NOT NULL,
	MODIFY_USER					VARCHAR(50) NOT NULL,
	MODIFY_TIME					DATETIME NOT NULL,
	
	SYS_STATUS					VARCHAR(1) NOT NULL,
	USERNAME					VARCHAR(100) NOT NULL,
	FIRSTNAME					VARCHAR(100),
	LASTNAME					VARCHAR(100),
	EMAIL						VARCHAR(200),
	DESCRIPTION					TEXT,
	LOCK_STATUS					VARCHAR(1) NOT NULL,
	PASSWORD					VARCHAR(100) NOT NULL,
	LOGIN_COUNT					INT NOT NULL,
	ERROR_COUNT					INT NOT NULL,
	CONTINUE_ERROR_COUNT		INT NOT NULL,
	LAST_CHANGE_PASSWORD_TIME	DATETIME NOT NULL,
	FIRST_LOGIN_TIME			DATETIME,
	LAST_LOGIN_TIME				DATETIME,
	EXPIRE_TIME					DATETIME NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- RB_ROLE
DROP TABLE IF EXISTS `RB_ROLE`;
CREATE TABLE IF NOT EXISTS `RB_ROLE` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER					VARCHAR(50) NOT NULL,
	CREATE_TIME					DATETIME NOT NULL,
	MODIFY_USER					VARCHAR(50) NOT NULL,
	MODIFY_TIME					DATETIME NOT NULL,
	
	SYS_STATUS					VARCHAR(1) NOT NULL,
	CODE						VARCHAR(100) NOT NULL,
	NAME						VARCHAR(100),
	DESCRIPTION					TEXT
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- RB_OPERATION
DROP TABLE IF EXISTS `RB_OPERATION`;
CREATE TABLE IF NOT EXISTS `RB_OPERATION` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER					VARCHAR(50) NOT NULL,
	CREATE_TIME					DATETIME NOT NULL,
	MODIFY_USER					VARCHAR(50) NOT NULL,
	MODIFY_TIME					DATETIME NOT NULL,
	
	SYS_STATUS					VARCHAR(1) NOT NULL,
	CODE						VARCHAR(100) NOT NULL,
	NAME						VARCHAR(100),
	DESCRIPTION					TEXT
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- RB_USER_ROLE
DROP TABLE IF EXISTS `RB_USER_ROLE`;
CREATE TABLE IF NOT EXISTS `RB_USER_ROLE` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	
	USER_ID						BIGINT NOT NULL,
	ROLE_ID						BIGINT NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- RB_USER_OPERATION
DROP TABLE IF EXISTS `RB_USER_OPERATION`;
CREATE TABLE IF NOT EXISTS `RB_USER_OPERATION` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	
	USER_ID						BIGINT NOT NULL,
	OPERATION_ID				BIGINT NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- RB_ROLE_OPERATION
DROP TABLE IF EXISTS `RB_ROLE_OPERATION`;
CREATE TABLE IF NOT EXISTS `RB_ROLE_OPERATION` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	
	ROLE_ID						BIGINT NOT NULL,
	OPERATION_ID				BIGINT NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
