-- ==================================================================
-- SAMPLE DATA
-- ==================================================================

-- RB_USER
INSERT INTO rb_user (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	USERNAME, FIRSTNAME, LASTNAME, EMAIL, DESCRIPTION,
	LOCK_STATUS, PASSWORD,
	LOGIN_COUNT, ERROR_COUNT, CONTINUE_ERROR_COUNT,
	LAST_CHANGE_PASSWORD_TIME, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, EXPIRE_TIME)
VALUES (
	1, 'SYSTEM', SYSDATE(), 'SYSTEM', SYSDATE(), 'Y',
	'admin', NULL, NULL, 'admin@softpower.com.tw', NULL,
	'N', '$2a$10$.mAivHSvvrO9MkQ77lGD5.WxVmj75qQG7dqcxzL2vRgr/IJOQmZqu',
	0, 0, 0,
	SYSDATE(), NULL, NULL, '2016-01-01'
);

INSERT INTO rb_user (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	USERNAME, FIRSTNAME, LASTNAME, EMAIL, DESCRIPTION,
	LOCK_STATUS, PASSWORD,
	LOGIN_COUNT, ERROR_COUNT, CONTINUE_ERROR_COUNT,
	LAST_CHANGE_PASSWORD_TIME, FIRST_LOGIN_TIME, LAST_LOGIN_TIME, EXPIRE_TIME)
VALUES (
	2, 'SYSTEM', SYSDATE(), 'SYSTEM', SYSDATE(), 'Y',
	'user', NULL, NULL, 'user@softpower.com.tw', NULL,
	'N', '$2a$10$749VfAYgJXAQm3FsOM4ixu8ItEC9cjwf0yAhEKdmJbvY6i.7u2nLC',
	0, 0, 0,
	SYSDATE(), null, null, '2016-01-01'
);


-- RB_ROLE
INSERT INTO rb_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	CODE, NAME, DESCRIPTION)
VALUES (
	1, 'TEST', SYSDATE(), 'TEST', SYSDATE(), 'Y',
	'ROLE_ADMIN', 'admin', 'administrator'
);

INSERT INTO rb_role (
	ID, CREATE_USER, CREATE_TIME, MODIFY_USER, MODIFY_TIME, SYS_STATUS,
	CODE, NAME, DESCRIPTION)
VALUES (
	2, 'TEST', SYSDATE(), 'TEST', SYSDATE(), 'Y',
	'ROLE_USER', 'user', 'user'
);


-- RB_USER_ROLE
INSERT INTO rb_user_role (
	ID, USER_ID, ROLE_ID)
VALUES (
	1, 1, 1
);

INSERT INTO rb_user_role (
	ID, USER_ID, ROLE_ID)
VALUES (
	2, 1, 2
);

INSERT INTO rb_user_role (
	ID, USER_ID, ROLE_ID)
VALUES (
	3, 2, 2
);
