-- ==================================================================
-- TABLES - MySQL
-- ==================================================================

-- JSLOG_USER
DROP TABLE IF EXISTS `JSLOG_USER`;
CREATE TABLE IF NOT EXISTS `JSLOG_USER` (
	ID					BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER			VARCHAR(50) NOT NULL,
	CREATE_TIME			DATETIME NOT NULL,
	MODIFY_USER			VARCHAR(50) NOT NULL,
	MODIFY_TIME			DATETIME NOT NULL,
	
	SYS_STATUS			VARCHAR(1) NOT NULL,
	NAME				VARCHAR(100) NOT NULL,
	EMAIL				VARCHAR(100),
	PASSWORD			VARCHAR(100) NOT NULL
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- JSLOG_APP
DROP TABLE IF EXISTS `JSLOG_APP`;
CREATE TABLE IF NOT EXISTS `JSLOG_APP` (
	ID					BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER			VARCHAR(50) NOT NULL,
	CREATE_TIME			DATETIME NOT NULL,
	MODIFY_USER			VARCHAR(50) NOT NULL,
	MODIFY_TIME			DATETIME NOT NULL,
	
	SYS_STATUS			VARCHAR(1) NOT NULL,
	NAME				VARCHAR(100) NOT NULL,
	APP_KEY				VARCHAR(100),
	SITE				VARCHAR(500)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- JSLOG_CLIENT
DROP TABLE IF EXISTS `JSLOG_CLIENT`;
CREATE TABLE IF NOT EXISTS `JSLOG_CLIENT` (
	ID							BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	
	NAVIGATOR_APP_VERSION		VARCHAR(100) NOT NULL,
	NAVIGATOR_COOKIE_ENABLED	VARCHAR(50),
	NAVIGATOR_LANGUAGE			VARCHAR(50),
	NAVIGATOR_PLATFORM			VARCHAR(50),
	NAVIGATOR_USER_AGENT		VARCHAR(100),
	NAVIGATOR_VENDOR			VARCHAR(50),
	
	SCREEN_WIDTH				SMALLINT,
	SCREEN_HEIGHT				SMALLINT,
	SCREEN_AVAIL_WIDTH			SMALLINT,
	SCREEN_AVAIL_HEIGHT			SMALLINT,
	SCREEN_COLOR_DEPTH			SMALLINT,
	SCREEN_PIXEL_DEPTH			SMALLINT,
	
	LOCATION_HREF				VARCHAR(500),
	LOCATION_HOSTNAME			VARCHAR(100),
	LOCATION_PATHNAME			VARCHAR(100),
	LOCATION_PROTOCOL			VARCHAR(50),
	
	DOCUMENT_WIDTH				SMALLINT,
	DOCUMENT_HEIGHT				SMALLINT
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- JSLOG_FEEDBACK
DROP TABLE IF EXISTS `JSLOG_FEEDBACK`;
CREATE TABLE IF NOT EXISTS `JSLOG_FEEDBACK` (
	ID					BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER			VARCHAR(50) NOT NULL,
	CREATE_TIME			DATETIME NOT NULL,
	MODIFY_USER			VARCHAR(50) NOT NULL,
	MODIFY_TIME			DATETIME NOT NULL,
	
	APP_ID				BIGINT,
	CLIENT_ID			BIGINT,
	SCREENSHOT_ID		BIGINT,
	
	SUBJECT				VARCHAR(100),
	CONTENT				TEXT
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- JSLOG_ONERROR
DROP TABLE IF EXISTS `JSLOG_ONERROR`;
CREATE TABLE IF NOT EXISTS `JSLOG_ONERROR` (
	ID					BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	CREATE_USER			VARCHAR(50) NOT NULL,
	CREATE_TIME			DATETIME NOT NULL,
	MODIFY_USER			VARCHAR(50) NOT NULL,
	MODIFY_TIME			DATETIME NOT NULL,
	
	APP_ID				BIGINT,
	CLIENT_ID			BIGINT,
	SCREENSHOT_ID		BIGINT,
	
	ERR_MSG				TEXT,
	URL					VARCHAR(500),
	LINE				INT,
	COL					INT,
	ERR_OBJ				VARCHAR(500)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- JSLOG_SCREENSHOT
DROP TABLE IF EXISTS `JSLOG_SCREENSHOT`;
CREATE TABLE IF NOT EXISTS `JSLOG_SCREENSHOT` (
	ID					BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
	
	MIME_TYPE			TEXT,
	STREAM				MEDIUMBLOB
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

